### ISSUE TITLE
ClassNotFoundException when requiring clj-exif-orientation

### ISSUE THREAD

**Issue by drpepper** [keeth/clj-exif-orientation#1]
Hello, your library seems perfect for my project, but I can't seem to require it without an immediate exception:

`java.lang.ClassNotFoundException: org.apache.commons.imaging.formats.tiff.constants.AllTagConstants, compiling:(clj_exif/core.clj:1:1)`

All I have so far is just the two required libraries in my `ns` statement, and the dependency in my project.clj file, installed with lein.

Any ideas, please? Thanks

**Comment by whamtet** [comment]
Just update clj-exif to the latest version, see

[pull request](https://github.com/keeth/clj-exif-orientation/pull/2)

**Comment by keeth** [comment]
merged, thanks!

**Comment by keeth** [comment]
released 0.2.1 on clojars
